/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package osproject2;

/**
 *
 * @author Valeria_Yasmin
 */
public class Interface extends javax.swing.JFrame {

    /** Creates new form Interface */
    public Interface() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Revision = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Repair = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        firstPriority = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        secondPriority = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        thirdPriority = new javax.swing.JTextArea();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fábrica Mattel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Revision.setEditable(false);
        Revision.setBackground(new java.awt.Color(46, 48, 49));
        Revision.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Revision.setForeground(new java.awt.Color(153, 255, 255));
        Revision.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Revision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevisionActionPerformed(evt);
            }
        });
        getContentPane().add(Revision, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, 40));

        Repair.setEditable(false);
        Repair.setBackground(new java.awt.Color(46, 48, 49));
        Repair.setColumns(10);
        Repair.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Repair.setForeground(new java.awt.Color(153, 255, 255));
        Repair.setRows(5);
        jScrollPane1.setViewportView(Repair);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 180, 130));

        firstPriority.setEditable(false);
        firstPriority.setBackground(new java.awt.Color(46, 48, 49));
        firstPriority.setColumns(10);
        firstPriority.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstPriority.setForeground(new java.awt.Color(153, 255, 255));
        firstPriority.setRows(5);
        jScrollPane2.setViewportView(firstPriority);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, 130));

        secondPriority.setEditable(false);
        secondPriority.setBackground(new java.awt.Color(46, 48, 49));
        secondPriority.setColumns(10);
        secondPriority.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        secondPriority.setForeground(new java.awt.Color(153, 255, 255));
        secondPriority.setRows(5);
        jScrollPane3.setViewportView(secondPriority);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 180, 130));

        thirdPriority.setEditable(false);
        thirdPriority.setBackground(new java.awt.Color(46, 48, 49));
        thirdPriority.setColumns(10);
        thirdPriority.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        thirdPriority.setForeground(new java.awt.Color(153, 255, 255));
        thirdPriority.setRows(5);
        jScrollPane4.setViewportView(thirdPriority);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 180, 130));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Final Background.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RevisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    public static javax.swing.JTextArea Repair;
    protected static javax.swing.JTextField Revision;
    public static javax.swing.JTextArea firstPriority;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextArea secondPriority;
    public static javax.swing.JTextArea thirdPriority;
    // End of variables declaration//GEN-END:variables

}
